### ISSUE TITLE
False positive on Kaocha

### ISSUE THREAD

**Issue by liquidz** [xsc/version-clj#12]
### Problem

Kaocha has a version like `1.0-612`, and this version is treated as the latest version by mistake.
https://github.com/lambdaisland/kaocha/releases

### How to reproduce

- v1.0.0
```clj
(require '[version-clj.core :as v])
(v/version-compare "1.0.732" "1.0-612") ;; => 1
```

- v2.0.0
```clj
(require '[version-clj.core :as v])
(v/version-compare "1.0.732" "1.0-612") ;; => -1
```

**Comment by xsc** [comment]
@liquidz My bad! That's a regression and I'll release a fixed version momentarily.

Versions are hard...

**Comment by xsc** [comment]
2.0.1 released! 🎉

**Comment by liquidz** [comment]
What a fast!! 
I'll have a look. Thanks!

**Comment by liquidz** [comment]
@xsc I confirmed 2.0.1 works perfectly.
Thanks so much for your awesome work!
